#!/usr/bin/env bash
# Render the Helm chart's CRD template from the controller-gen output.
#
# The single source of truth for the SpillwayProfile CRD is
# config/crd/spillway.kroy.io_spillwayprofiles.yaml, generated by
#   go tool controller-gen crd paths=./api/... output:crd:dir=config/crd
# from the kubebuilder markers in api/v1 and api/v1alpha1. This script wraps that file in
# the chart's template scaffolding (installCRDs guard, common labels,
# helm.sh/resource-policy annotation) and writes
# charts/spillway/templates/crd.yaml. Never edit the chart file by hand.
#
# Usage:
#   hack/sync-crd.sh          rewrite the chart file (no-op if already current)
#   hack/sync-crd.sh --check  exit 1 with a diff if the chart file is stale
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="${REPO_ROOT}/config/crd/spillway.kroy.io_spillwayprofiles.yaml"
DST="${REPO_ROOT}/charts/spillway/templates/crd.yaml"

mode="write"
case "${1:-}" in
  "") ;;
  --check) mode="check" ;;
  -h|--help)
    sed -n '2,15p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
    exit 0
    ;;
  *)
    echo "unknown argument: $1 (expected --check or nothing)" >&2
    exit 2
    ;;
esac

if [[ ! -f "${SRC}" ]]; then
  echo "missing generated CRD: ${SRC}" >&2
  echo "run: go tool controller-gen crd paths=./api/... output:crd:dir=config/crd" >&2
  exit 1
fi

# Sanity-check the source: exactly one CRD document, with the sections we
# splice on either side of the metadata block.
if [[ "$(grep -c '^kind: CustomResourceDefinition$' "${SRC}")" -ne 1 ]]; then
  echo "${SRC}: expected exactly one CustomResourceDefinition document" >&2
  exit 1
fi
if ! grep -q '^spec:$' "${SRC}"; then
  echo "${SRC}: missing top-level spec:" >&2
  exit 1
fi

crd_name="$(awk '/^metadata:$/ { m = 1; next } m && /^  name: / { print $2; exit }' "${SRC}")"
if [[ -z "${crd_name}" ]]; then
  echo "${SRC}: could not find metadata.name" >&2
  exit 1
fi

# controller-gen stamps its version as an annotation; carry it over so the
# installed CRD records which generator produced it.
gen_version="$(awk '/^    controller-gen.kubebuilder.io\/version: / { print $2; exit }' "${SRC}")"

render() {
  cat <<EOF
{{- /* Generated from config/crd/$(basename "${SRC}") by hack/sync-crd.sh. DO NOT EDIT. Regenerate with: hack/sync-crd.sh */}}
{{- if .Values.installCRDs }}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ${crd_name}
  labels:
    {{- include "spillway.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
EOF
  if [[ -n "${gen_version}" ]]; then
    echo "    controller-gen.kubebuilder.io/version: ${gen_version}"
  fi
  # Everything from the top-level spec: onward is copied verbatim.
  awk 'f { print } /^spec:$/ { f = 1; print }' "${SRC}"
  echo '{{- end }}'
}

tmp="$(mktemp)"
trap 'rm -f "${tmp}"' EXIT
render > "${tmp}"

if [[ "${mode}" == "check" ]]; then
  if [[ ! -f "${DST}" ]]; then
    echo "chart CRD template is missing: ${DST}" >&2
    echo "run: hack/sync-crd.sh" >&2
    exit 1
  fi
  if ! diff -u "${DST}" "${tmp}" --label "${DST#"${REPO_ROOT}/"}" --label "rendered from ${SRC#"${REPO_ROOT}/"}"; then
    echo >&2
    echo "chart CRD template is stale; run: hack/sync-crd.sh" >&2
    exit 1
  fi
  echo "chart CRD template is up to date"
  exit 0
fi

if [[ -f "${DST}" ]] && cmp -s "${tmp}" "${DST}"; then
  echo "unchanged: ${DST#"${REPO_ROOT}/"}"
else
  cp "${tmp}" "${DST}"
  echo "wrote: ${DST#"${REPO_ROOT}/"}"
fi
