# Basic Secret replication — copy to all non-system namespaces.
apiVersion: v1
kind: Secret
metadata:
  name: shared-api-token
  namespace: platform
  annotations:
    spillway.kroy.io/replicate-to: "all"
type: Opaque
stringData:
  token: replace-me
